name: CI
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: coverage
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: "Deploy with gcloud"
        uses: actions-hub/gcloud@master
        env:
          APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
          GCP_CF_NAME: ${{secrets.}}
          GCP_CF_ENTRY_POINT: ${{secrets.}}
          GCP_CF_RUNTIME: ${{secrets.}}
          GCP_CF_REGION: ${{secrets.}}
          GCP_CF_MEMORY: ${{secrets.}}
          GCP_CF_MAX_INSTANCES: ${{secrets.}}
          APP_API_KEY: ${{secrets.}}
        with:
          cmd: ./scripts/deploy.sh